version: '3.9'

services:
  attribution-service:
    build:
      context: ./backend  # Path to your Java project directory
    ports:
      - "8081:8081"
    networks:
      - ctv-network
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data

  postgres:
    image: postgres:15-alpine
    networks:
      - ctv-network
    environment:
      POSTGRES_DB: ctv_analytics
      POSTGRES_USER: ctv_user
      POSTGRES_PASSWORD: securepassword
    volumes:
      - pgdata:/var/lib/postgresql/data

  nginx:
    image: nginx:1.25-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/ctv.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - ctv-network
    depends_on:
      - attribution-service

networks:
  ctv-network:
    driver: bridge

volumes:
  pgdata: